import Navbar from '@/components/Navbar'
import './globals.css'
import { Open_Sans } from 'next/font/google'
import Footer from '@/components/Footer'

// const inter = Inter({ subsets: ['latin'] })
const openSans = Open_Sans({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
})
export const metadata = {
  title: 'Embassy Dental',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`${openSans.className} scroll-smooth`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
