import './globals.css'
import { Jost } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const jost = Jost({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`${jost.className} scroll-smooth`}>{children}</body>
    </html>
  )
}
